### PR TITLE
move off Errors wherever possible to Exceptions

### LINKED ISSUE #802: should throw exceptions instead of errors
Errors mean very serious system-level problems that could abort the program. Since mapdb is a component in a larger system, it should not throw Errors, but instead Exceptions. Looking at the descriptions of a few, especially IllegalAccessError, it's clear that these aren't to be thrown lightly.

### PR DESCRIPTION
**Pull request by roxchkplusony**
Fixes #802. If it is reasonable to put this into the release-3.0 line, I'll be glad to re-integrate.

### CODE REVIEW

**Comment by roxchkplusony** [comment]
@jankotek FYI

**Comment by roxchkplusony** [comment]
@jankotek mind taking a look at this issue+fix?

**Comment by jankotek** [comment]
will have a look soon

**Comment by jankotek** [comment]
Need to decide how Exception vs Errors will be handled in 3.1 release.

This change will not go into 3.0 branch. 

There was a typo.

**Comment by roxchkplusony** [comment]
@jankotek so sorry for the super long delay. I don't even remember where I left off! But I've rebased and would love you to have a second look. All changes I made away from Errors were to reasonable RuntimeExceptions, including where appropriate to mapdb ones. For example, I did not change IOError to IOException, but rather threw things like VolumeIOExceptions

**Comment by jankotek** [comment]
Hi, please write patches against mapdb4 branch. 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/jankotek/
> mapdb","title":"jankotek/mapdb","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/jankotek/mapdb"}},"updates":{"snipp
> ets":[{"icon":"PERSON","message":"@roxchkplusony in #803: @jankotek
> so sorry for the super long delay. I don't even remember where I left
> off! But I've rebased and would love you to have a second look. All
> changes I made away from Errors were to reasonable RuntimeExceptions,
> including where appropriate to mapdb ones. For example, I did not
> change IOError to IOException, but rather threw things like
> VolumeIOExceptions"}],"action":{"name":"View Pull
> Request","url":"https://github.com/jankotek/mapdb/pull/803#issuecomme
> nt-310768720"}}}

**Comment by roxchkplusony** [comment]
Yessir!

**Comment by roxchkplusony** [comment]
@jankotek this rebase is done!

**Comment by roxchkplusony** [comment]
@jankotek i'm running into conflicts. Can we see about getting this in soon?

**Comment by jankotek** [comment]
Thanks and sorry it tooks so long.

**Comment by jankotek** [comment]
Thanks, and sorry it took so long to merge

**Comment by roxchkplusony** [comment]
All good, thank you!

**Pull request merged**
