### PR TITLE
Fix StoreDirect compact when index pages overflow > 1

### PR DESCRIPTION
**Pull request by mschirmer84**
If indexPages > 1 compact for StoreDirect would fail. I have fixed the math and written a test to make sure the data is not corrupted after random deletes and a compact.

I also noticed there are 8 unused bytes at the start of the first index page after the head because of recidToOffset(long recid) math. I haven't attempted to fix this though.

### CODE REVIEW

**Comment by mschirmer84** [comment]
The first of the two tests could potentially be removed. The second test covers the first one and more.

**Comment by mschirmer84** [comment]
Never mind my comment about the 8 unused bytes at the start of the first index page. I completely missed the comments in recidToOffset. I understand now. My pull request is still valid to fix StoreDirect compaction.

**Comment by jankotek** [comment]
Wow, someone can actually read that storage stuff :-) Will review & merge today or tomorrow. 

Also not sure you know it, but there storage format specification, it is probably outdated for WAL. http://www.mapdb.org/doc/format.html

**Comment by mschirmer84** [comment]
Thanks for the compliment. I took some time to read the format today. I've added some code clarity to the pull request.

**Comment by jankotek** [comment]
Nice works, thanks

**Pull request merged**
