### PR TITLE
Fix NPE for interfaces in SerializerPojo#getFields

### PR DESCRIPTION
**Pull request by KaiStapel**
Proposed fix for https://github.com/jankotek/mapdb/issues/653

### CODE REVIEW

**Comment by jankotek** [comment]
Already fixed. I used your patch, but had to reformat it.

**Comment by KaiStapel** [comment]
Thanks a lot. Will this be part of 1.0.9? If so, is there any release date yet?

**Comment by jankotek** [comment]
1.0.9 is coming today or tomorrow. Just writing release notes.

**Comment by KaiStapel** [comment]
Wow. Perfect!

**Pull request closed without merging**
